import type { SiteContent } from "./types";
import { DEFAULT_POSTS } from "./default-posts";
import { LOCAL_POSTS } from "./local-posts";

// Seed content used until the admin saves their own. Facts about the gym come
// from its public listings (Google Business Profile, Justdial, Instagram).
// Anything the owner should confirm — prices, trainers, hours — is editable
// in /admin and is phrased so it does not over-promise.

export const DEFAULT_CONTENT: SiteContent = {
  business: {
    name: "Royal Fitness Club",
    shortName: "Royal Fitness",
    tagline: "Train Like Royalty in Sector 93, Noida",
    description:
      "Royal Fitness Club is a fully air-conditioned gym in Gejha, Sector 93, Noida with certified trainers, modern strength and cardio equipment, personal training, fat-loss and muscle-gain programs. Serving the neighbourhood since 2019.",
    foundedYear: 2019,
    phone: "+91 88518 30081",
    altPhone: "",
    whatsapp: "918851830081",
    email: "",
    instagram: "royalfitness93_",
    googleMapsUrl: "https://www.google.com/maps?cid=9789213701935789540",
    googleReviewUrl: "https://www.google.com/maps?cid=9789213701935789540",
    mapEmbedUrl:
      "https://maps.google.com/maps?q=Royal%20Fitness%20Club%2C%20Gejha%2C%20Sector%2093%2C%20Noida&z=16&output=embed",
    address: {
      street: "Main Road, near Gali No. 3, Gejha Village",
      locality: "Sector 93",
      city: "Noida",
      region: "Uttar Pradesh",
      postalCode: "201304",
      country: "IN",
    },
    geo: { lat: 28.5234, lng: 77.3833 },
    hours: [
      { label: "Morning", days: "Monday – Saturday", open: "05:30", close: "11:00" },
      { label: "Evening", days: "Monday – Saturday", open: "16:00", close: "22:00" },
    ],
    rating: { value: 4.7, count: 303, source: "Justdial" },
    priceRange: "₹₹",
  },
  hero: {
    eyebrow: "Sector 93 · Noida · Since 2019",
    title: "Build a body",
    highlight: "worthy of the crown",
    subtitle:
      "Certified trainers, heavy-duty strength floor, cardio zone and fully air-conditioned space — right on Gejha Main Road. Your first session is on us.",
    primaryCta: "Book a Free Trial",
    secondaryCta: "See Membership Plans",
    image: "",
  },
  stats: [
    { value: 2019, suffix: "", label: "Serving Noida since" },
    { value: 4.7, suffix: "★", label: "Average rating" },
    { value: 303, suffix: "+", label: "Member reviews" },
    { value: 2, suffix: " batches", label: "Morning & evening, Mon–Sat" },
  ],
  programs: [
    {
      id: "strength",
      title: "Strength & Bodybuilding",
      icon: "Dumbbell",
      summary: "Progressive-overload programming on free weights, racks and machines for real, visible muscle.",
      points: ["Split routines by goal", "Form checks on every big lift", "Monthly progress tracking"],
      image: "",
    },
    {
      id: "fat-loss",
      title: "Fat Loss & Transformation",
      icon: "Flame",
      summary: "Structured fat-loss blocks mixing weights, HIIT and a practical Indian diet guide.",
      points: ["Calorie & macro targets", "Weekly weigh-ins", "Home-food friendly diet charts"],
      image: "",
    },
    {
      id: "personal-training",
      title: "Personal Training",
      icon: "UserCheck",
      summary: "One-on-one coaching with a certified trainer who plans, spots and pushes every session.",
      points: ["Custom plan for your body", "Injury-aware exercise choice", "Accountability that works"],
      image: "",
    },
    {
      id: "cardio",
      title: "Cardio & Conditioning",
      icon: "HeartPulse",
      summary: "Treadmills, cycles and cross-trainers plus circuits that build stamina and heart health.",
      points: ["Heart-rate zone training", "Circuit & functional sessions", "Endurance for sports"],
      image: "",
    },
    {
      id: "diet",
      title: "Diet & Nutrition Guidance",
      icon: "Salad",
      summary: "Veg and non-veg Indian meal plans built around ghar ka khana — no fad diets.",
      points: ["Protein targets for vegetarians", "Supplement advice without upselling", "Simple meal swaps"],
      image: "",
    },
    {
      id: "women",
      title: "Women's Fitness",
      icon: "Sparkles",
      summary: "Safe, supportive training for toning, strength, PCOS-friendly fat loss and posture.",
      points: ["Beginner-friendly progressions", "Guided strength training", "Comfortable, CCTV-secured space"],
      image: "",
    },
  ],
  plans: [
    {
      id: "monthly",
      name: "Monthly",
      duration: "1 month",
      price: 2000,
      couplePrice: 3000,
      originalPrice: 0,
      perks: ["Full gym floor access", "Cardio & strength zones", "Trainer guidance on the floor", "Morning & evening batches"],
      featured: false,
    },
    {
      id: "quarterly",
      name: "Quarterly",
      duration: "3 months",
      price: 5000,
      couplePrice: 7500,
      originalPrice: 0,
      perks: ["Everything in Monthly", "Basic diet guidance", "Progress check-ins"],
      featured: false,
    },
    {
      id: "half-yearly",
      name: "Half-Yearly",
      duration: "6 months",
      price: 8000,
      couplePrice: 12000,
      originalPrice: 0,
      perks: ["Everything in Quarterly", "Personalised workout plan", "Monthly progress review"],
      featured: false,
    },
    {
      id: "yearly",
      name: "Annual",
      duration: "12 months",
      price: 14000,
      couplePrice: 21000,
      originalPrice: 0,
      perks: ["Everything in Half-Yearly", "Custom Indian diet plan", "Priority trainer support"],
      featured: true,
    },
    {
      id: "fifteen-months",
      name: "Royal 15",
      duration: "15 months",
      price: 16000,
      couplePrice: 24000,
      originalPrice: 0,
      perks: ["Everything in Annual", "3 extra months for ₹2,000 more", "Lowest price per month"],
      featured: false,
    },
  ],
  planNote:
    "Couple price applies when two people join together. Personal training is quoted separately — call or WhatsApp us for details.",
  trainers: [
    {
      id: "head-coach",
      name: "Aman Sharma",
      role: "Founder",
      bio: "Founder of Royal Fitness Club — building a serious, well-equipped neighbourhood gym for Gejha and Sector 93, Noida.",
      image: "/gallery/aman-sharma-royal-fitness-gym.webp",
      specialties: ["Strength", "Body transformation", "Nutrition"],
      instagram: "royalfitness93_",
    },
  ],
  gallery: [
    { id: "g-rule", title: "Rule Your Strength", caption: "Aman Sharma, founder of Royal Fitness Club", image: "/gallery/aman-sharma-rule-your-strength.webp" },
    { id: "g-back", title: "Built Like Royalty", caption: "Back and arm conditioning — Aman Sharma", image: "/gallery/aman-sharma-back-pose.webp" },
    { id: "g-gym", title: "Train Above Average", caption: "Aman Sharma on the strength floor", image: "/gallery/aman-sharma-royal-fitness-gym.webp" },
    { id: "g-crown", title: "Earn The Crown", caption: "Stage-ready physique — Aman Sharma", image: "/gallery/aman-sharma-physique.webp" },
    { id: "g-grind", title: "Grind. Conquer. Repeat.", caption: "Aman Sharma between sets", image: "/gallery/aman-sharma-grind-conquer-repeat.webp" },
    { id: "g-eagle", title: "Eagles Fly Alone", caption: "Chest fly day — Aman Sharma", image: "/gallery/aman-sharma-eagles-fly-alone.webp" },
    { id: "g-story", title: "Rewrite Your Story", caption: "Aman Sharma, founder of Royal Fitness Club", image: "/gallery/aman-sharma-rewrite-your-story.webp" },
    { id: "g-chest", title: "Royal Mind. Savage Body.", caption: "Chest and shoulder detail — Aman Sharma", image: "/gallery/aman-sharma-chest-shoulders.webp" },
    { id: "g-backflex", title: "Built From the Back", caption: "Back and triceps — Aman Sharma", image: "/gallery/aman-sharma-back-flex.webp" },
    { id: "g-rest", title: "Earn Every Rep", caption: "Catching breath between sets — Aman Sharma", image: "/gallery/aman-sharma-between-sets.webp" },
  ],
  testimonials: [],
  faqs: [
    {
      id: "couple",
      q: "Do you have couple memberships?",
      a: "Yes. Couples joining together pay 1.5× the single price — for example ₹3,000 a month for two instead of ₹4,000, or ₹21,000 a year for two instead of ₹28,000.",
    },
    {
      id: "fees",
      q: "What are the gym fees?",
      a: "Plans start at ₹2,000 for one month. Longer plans cost less per month: ₹5,000 for 3 months, ₹8,000 for 6 months, ₹14,000 for 12 months and ₹16,000 for 15 months. Couples joining together pay 1.5× the single price.",
    },
    {
      id: "trial",
      q: "Can I try the gym before joining?",
      a: "Yes. Book a free trial session using the form or WhatsApp us — a trainer will show you around and take you through a workout.",
    },
    {
      id: "location",
      q: "Where exactly is Royal Fitness Club?",
      a: "We are on Main Road, near Gali No. 3, Gejha Village, Sector 93, Noida 201304 — easy to reach from Sector 93A, 93B, Gejha, Sector 100 and the Noida Expressway side.",
    },
    {
      id: "timings",
      q: "What are the gym timings?",
      a: "Monday to Saturday we run two batches: morning 5:30 AM – 11:00 AM and evening 4:00 PM – 10:00 PM. Sunday is off. Timings can change on festivals, so check our Instagram or call before visiting.",
    },
    {
      id: "beginner",
      q: "I have never been to a gym. Is it okay for beginners?",
      a: "Absolutely. Most members start as beginners. Our certified trainers teach form first, start you on light loads and progress you safely.",
    },
    {
      id: "ac",
      q: "Is the gym air-conditioned and safe?",
      a: "Yes — the whole floor is air-conditioned, CCTV-monitored and has a marked emergency exit.",
    },
    {
      id: "diet",
      q: "Do you provide diet plans?",
      a: "Quarterly and longer memberships include diet guidance built around normal Indian home food, for both vegetarians and non-vegetarians.",
    },
  ],
  posts: [...DEFAULT_POSTS, ...LOCAL_POSTS],
  seo: {
    title: "Royal Fitness Club — Best Gym in Sector 93, Noida",
    description:
      "Royal Fitness Club, Gejha Sector 93 Noida: AC gym with certified trainers, personal training, fat loss & muscle gain programs. Rated 4.7★ by 300+ members. Book a free trial.",
    keywords: [
      "gym in sector 93 noida",
      "gym near me noida",
      "best gym in noida",
      "royal fitness club noida",
      "gym in gejha",
      "personal trainer noida",
      "fat loss gym noida",
      "gym near sector 93a",
      "gym near sector 100 noida",
      "women gym noida",
    ],
    ogImage: "",
    googleVerification: "",
  },
  theme: { primary: "#e8394b", secondary: "#04466d" },
  announcement: "Couple membership: train together from ₹3,000/month for two · Free trial for new members",
};
