import type { MetadataRoute } from "next";
import { SITE } from "@/lib/site";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: [
          "/",
          "/diseases/",
          "/herbs/",
          "/medicines/",
          "/nutrition/",
          "/blog/",
          "/blog/category/",
          "/blog/latest",
          "/blog/trending",
          "/blog/search",
          "/blog/author",
          "/products/",
          "/ayurveda/",
          "/thali-builder",
          "/millet-swap",
          "/health-qa",
          "/live-advisory",
          "/dosha-meals",
          "/fasting-planner",
          "/hinglish-search",
          "/india-risk",
          "/yoga-timer",
          "/ritucharya",
          "/herb-interaction",
          "/barcode-scanner",
          "/child-growth",
          "/food-database",
          "/health-search",
          "/drug-lookup",
          "/exercises",
          "/nutrition-tracker",
          "/workout-builder",
          "/premium",
          "/deals",
          "/earn",
          "/lead",
          "/referral",
          "/about",
          "/contact",
          "/yoga",
          "/health-calculators",
          "/lab-tests",
          "/symptoms",
          "/search",
          // Monetization public routes — SEO optimized, must be crawlable
          "/affiliate-products/",
          "/store/",
          "/providers/",
          "/newsletter",
          "/consultation",
          "/partner-with-us",
          "/advertise",
        ],
        disallow: [
          "/api/",
          "/admin/",
          "/profile",
          "/login",
          "/register",
          // Private monetization — orders, purchases, secure download tokens
          "/orders",
          "/my-purchases",
          "/download/",
          "/api/monetization/download/",
          "/api/monetization/orders",
          "/api/monetization/leads",
        ],
      },
      {
        userAgent: "Googlebot",
        allow: "/",
        disallow: ["/api/", "/admin/"],
      },
      {
        userAgent: "Googlebot-Image",
        allow: "/",
      },
      {
        userAgent: "Bingbot",
        allow: "/",
        disallow: ["/api/", "/admin/"],
      },
    ],
    sitemap: [`${SITE.url}/sitemap.xml`],
    host: SITE.url,
  };
}
