// Curated exercise library used by /exercises and the workout planner.
// Kept local (no external API) so pages are fast, indexable and never break.

export type Muscle = "chest" | "back" | "shoulders" | "biceps" | "triceps" | "quads" | "hamstrings" | "glutes" | "calves" | "core" | "cardio";
export type Equipment = "barbell" | "dumbbell" | "machine" | "cable" | "bodyweight" | "kettlebell";
export type Level = "beginner" | "intermediate" | "advanced";

export type Exercise = {
  slug: string;
  name: string;
  primary: Muscle;
  secondary: Muscle[];
  equipment: Equipment;
  level: Level;
  kind: "compound" | "isolation" | "cardio";
  summary: string;
  steps: string[];
  tips: string[];
  mistakes: string[];
};

export const MUSCLES: { id: Muscle; label: string }[] = [
  { id: "chest", label: "Chest" },
  { id: "back", label: "Back" },
  { id: "shoulders", label: "Shoulders" },
  { id: "biceps", label: "Biceps" },
  { id: "triceps", label: "Triceps" },
  { id: "quads", label: "Quads" },
  { id: "hamstrings", label: "Hamstrings" },
  { id: "glutes", label: "Glutes" },
  { id: "calves", label: "Calves" },
  { id: "core", label: "Core / Abs" },
  { id: "cardio", label: "Cardio" },
];

export const EQUIPMENT: { id: Equipment; label: string }[] = [
  { id: "barbell", label: "Barbell" },
  { id: "dumbbell", label: "Dumbbell" },
  { id: "machine", label: "Machine" },
  { id: "cable", label: "Cable" },
  { id: "kettlebell", label: "Kettlebell" },
  { id: "bodyweight", label: "Bodyweight" },
];

const LEVEL_RANK: Record<Level, number> = { beginner: 0, intermediate: 1, advanced: 2 };
export const levelAtMost = (ex: Exercise, level: Level) => LEVEL_RANK[ex.level] <= LEVEL_RANK[level];

export const EXERCISES: Exercise[] = [
  // ---------- chest ----------
  {
    slug: "barbell-bench-press",
    name: "Barbell Bench Press",
    primary: "chest",
    secondary: ["triceps", "shoulders"],
    equipment: "barbell",
    level: "intermediate",
    kind: "compound",
    summary: "The classic upper-body strength builder for chest, front shoulders and triceps.",
    steps: [
      "Lie on the bench with eyes under the bar, feet flat and shoulder blades squeezed together.",
      "Grip slightly wider than shoulder width and unrack with straight arms.",
      "Lower the bar under control to your mid-chest, elbows about 45° from your body.",
      "Press back up to straight arms, keeping your back and glutes on the bench.",
    ],
    tips: ["Keep a slight arch and tight upper back", "Always use a spotter or safety pins when going heavy"],
    mistakes: ["Bouncing the bar off the chest", "Flaring elbows out to 90°"],
  },
  {
    slug: "dumbbell-bench-press",
    name: "Dumbbell Bench Press",
    primary: "chest",
    secondary: ["triceps", "shoulders"],
    equipment: "dumbbell",
    level: "beginner",
    kind: "compound",
    summary: "A shoulder-friendly press that fixes left–right strength imbalances.",
    steps: [
      "Sit with dumbbells on your thighs, then lie back and bring them to chest level.",
      "Press both dumbbells up until arms are straight above your chest.",
      "Lower slowly until elbows are just below bench level.",
      "Press back up, bringing the dumbbells slightly together at the top.",
    ],
    tips: ["Control the lowering for 2–3 seconds", "Keep wrists stacked over elbows"],
    mistakes: ["Letting dumbbells drift toward the face", "Using a range so deep it hurts the shoulders"],
  },
  {
    slug: "incline-dumbbell-press",
    name: "Incline Dumbbell Press",
    primary: "chest",
    secondary: ["shoulders", "triceps"],
    equipment: "dumbbell",
    level: "beginner",
    kind: "compound",
    summary: "Targets the upper chest for a fuller, more balanced chest shape.",
    steps: ["Set the bench to 30°.", "Press dumbbells up from upper-chest level.", "Lower under control to the sides of your upper chest.", "Press back to the start."],
    tips: ["30° is enough — steeper turns it into a shoulder press", "Keep your shoulder blades pinned"],
    mistakes: ["Bench set too steep", "Half reps"],
  },
  {
    slug: "push-up",
    name: "Push-Up",
    primary: "chest",
    secondary: ["triceps", "shoulders", "core"],
    equipment: "bodyweight",
    level: "beginner",
    kind: "compound",
    summary: "Anywhere chest and core exercise — scale it from knee push-ups to weighted.",
    steps: ["Hands slightly wider than shoulders, body in a straight line.", "Lower until your chest is a fist away from the floor.", "Push the floor away to straight arms."],
    tips: ["Squeeze glutes to keep hips level", "Elevate hands on a bench to make it easier"],
    mistakes: ["Sagging hips", "Head poking forward"],
  },
  {
    slug: "cable-fly",
    name: "Cable Fly",
    primary: "chest",
    secondary: ["shoulders"],
    equipment: "cable",
    level: "beginner",
    kind: "isolation",
    summary: "Constant-tension chest isolation that finishes a push workout.",
    steps: ["Set pulleys at shoulder height and step forward in a split stance.", "With a soft bend in the elbows, bring handles together in front of the chest.", "Return slowly until you feel a stretch across the chest."],
    tips: ["Think of hugging a big tree", "Keep the elbow angle fixed"],
    mistakes: ["Turning it into a press", "Going too heavy and losing the stretch"],
  },
  // ---------- back ----------
  {
    slug: "deadlift",
    name: "Conventional Deadlift",
    primary: "back",
    secondary: ["glutes", "hamstrings", "core"],
    equipment: "barbell",
    level: "advanced",
    kind: "compound",
    summary: "The king of posterior-chain strength — back, glutes and hamstrings together.",
    steps: [
      "Stand with mid-foot under the bar, feet hip-width apart.",
      "Hinge down and grip just outside your legs; shins touch the bar.",
      "Brace your core, flatten your back and pull the slack out of the bar.",
      "Push the floor away and stand tall, then lower the bar along your legs.",
    ],
    tips: ["Keep the bar in contact with your legs", "Learn it with a trainer before going heavy"],
    mistakes: ["Rounding the lower back", "Jerking the bar off the floor"],
  },
  {
    slug: "lat-pulldown",
    name: "Lat Pulldown",
    primary: "back",
    secondary: ["biceps"],
    equipment: "cable",
    level: "beginner",
    kind: "compound",
    summary: "Builds back width and prepares beginners for pull-ups.",
    steps: ["Grip the bar slightly wider than shoulders and sit with thighs locked in.", "Lean back slightly and pull the bar to your upper chest.", "Control it back up to straight arms."],
    tips: ["Lead with your elbows, not your hands", "Pause briefly at the bottom"],
    mistakes: ["Pulling behind the neck", "Swinging the torso"],
  },
  {
    slug: "pull-up",
    name: "Pull-Up",
    primary: "back",
    secondary: ["biceps", "core"],
    equipment: "bodyweight",
    level: "intermediate",
    kind: "compound",
    summary: "The best bodyweight back builder. Use bands or negatives to progress.",
    steps: ["Hang from the bar with an overhand grip.", "Pull your chest toward the bar until your chin clears it.", "Lower all the way down with control."],
    tips: ["Start with slow 5-second negatives if you can't do one yet", "Keep ribs down"],
    mistakes: ["Kipping or swinging", "Half reps"],
  },
  {
    slug: "seated-cable-row",
    name: "Seated Cable Row",
    primary: "back",
    secondary: ["biceps"],
    equipment: "cable",
    level: "beginner",
    kind: "compound",
    summary: "Mid-back thickness and posture — great for desk workers.",
    steps: ["Sit tall with a slight knee bend, holding the V-handle.", "Row the handle to your belly while squeezing shoulder blades together.", "Let your arms extend fully without rounding forward."],
    tips: ["Keep your chest up", "Pause and squeeze for a second"],
    mistakes: ["Rocking the torso", "Shrugging the shoulders"],
  },
  {
    slug: "one-arm-dumbbell-row",
    name: "One-Arm Dumbbell Row",
    primary: "back",
    secondary: ["biceps", "core"],
    equipment: "dumbbell",
    level: "beginner",
    kind: "compound",
    summary: "Unilateral row for lats and upper back with built-in core work.",
    steps: ["Place one knee and hand on a bench, back flat.", "Row the dumbbell toward your hip.", "Lower until the arm is straight."],
    tips: ["Pull to the hip, not the shoulder", "Keep hips square to the floor"],
    mistakes: ["Twisting the torso to lift more", "Rounded back"],
  },
  {
    slug: "barbell-row",
    name: "Barbell Bent-Over Row",
    primary: "back",
    secondary: ["biceps", "hamstrings", "core"],
    equipment: "barbell",
    level: "intermediate",
    kind: "compound",
    summary: "Heavy horizontal pull for a thick, strong back.",
    steps: ["Hinge forward to about 45° with a flat back.", "Row the bar to your lower chest.", "Lower with control, keeping the hinge."],
    tips: ["Brace hard before each rep", "Keep the neck neutral"],
    mistakes: ["Standing up more every rep", "Using momentum"],
  },
  // ---------- shoulders ----------
  {
    slug: "overhead-press",
    name: "Standing Overhead Press",
    primary: "shoulders",
    secondary: ["triceps", "core"],
    equipment: "barbell",
    level: "intermediate",
    kind: "compound",
    summary: "Full-body pressing strength with strong shoulders and core.",
    steps: ["Hold the bar at collarbone height, grip just outside shoulders.", "Squeeze glutes and press the bar straight overhead.", "Move your head back slightly to let the bar pass, then through once it clears.", "Lower to the collarbone."],
    tips: ["Squeeze glutes to protect the lower back", "Finish with biceps by the ears"],
    mistakes: ["Leaning way back", "Pressing the bar forward instead of up"],
  },
  {
    slug: "dumbbell-shoulder-press",
    name: "Seated Dumbbell Shoulder Press",
    primary: "shoulders",
    secondary: ["triceps"],
    equipment: "dumbbell",
    level: "beginner",
    kind: "compound",
    summary: "Beginner-friendly shoulder builder with a supported back.",
    steps: ["Sit on an upright bench with dumbbells at shoulder height.", "Press up until arms are nearly straight.", "Lower back to ear level."],
    tips: ["Keep forearms vertical", "Don't clash the dumbbells at the top"],
    mistakes: ["Arching off the bench", "Lowering too far and losing tension"],
  },
  {
    slug: "lateral-raise",
    name: "Dumbbell Lateral Raise",
    primary: "shoulders",
    secondary: [],
    equipment: "dumbbell",
    level: "beginner",
    kind: "isolation",
    summary: "Builds side delts for broader-looking shoulders.",
    steps: ["Stand with light dumbbells at your sides.", "Raise arms out to the sides until they're shoulder height.", "Lower slowly."],
    tips: ["Lead with the elbows", "Use light weight and strict form"],
    mistakes: ["Shrugging", "Swinging the weights up"],
  },
  {
    slug: "face-pull",
    name: "Cable Face Pull",
    primary: "shoulders",
    secondary: ["back"],
    equipment: "cable",
    level: "beginner",
    kind: "isolation",
    summary: "Rear delts and rotator cuff — keeps shoulders healthy for pressing.",
    steps: ["Set a rope at face height.", "Pull the rope toward your face, splitting the ends apart.", "Finish with hands beside your ears, then return."],
    tips: ["Pull the rope apart, not just back", "Great as a warm-up too"],
    mistakes: ["Going heavy and leaning back", "Pulling to the chest"],
  },
  // ---------- arms ----------
  {
    slug: "barbell-curl",
    name: "Barbell Curl",
    primary: "biceps",
    secondary: [],
    equipment: "barbell",
    level: "beginner",
    kind: "isolation",
    summary: "Straightforward, heavy-loadable biceps builder.",
    steps: ["Stand holding the bar with an underhand grip.", "Curl the bar up while keeping elbows by your sides.", "Lower all the way down slowly."],
    tips: ["Keep elbows pinned", "Control the lowering"],
    mistakes: ["Swinging the hips", "Cutting the range short"],
  },
  {
    slug: "hammer-curl",
    name: "Dumbbell Hammer Curl",
    primary: "biceps",
    secondary: [],
    equipment: "dumbbell",
    level: "beginner",
    kind: "isolation",
    summary: "Neutral-grip curl that builds biceps and forearms.",
    steps: ["Hold dumbbells with palms facing each other.", "Curl up without rotating the wrists.", "Lower slowly."],
    tips: ["Alternate arms to focus on each side"],
    mistakes: ["Elbows drifting forward"],
  },
  {
    slug: "triceps-pushdown",
    name: "Cable Triceps Pushdown",
    primary: "triceps",
    secondary: [],
    equipment: "cable",
    level: "beginner",
    kind: "isolation",
    summary: "Simple, joint-friendly triceps isolation.",
    steps: ["Hold a rope or bar at chest height with elbows at your sides.", "Push down until arms are straight.", "Return until forearms are just above parallel."],
    tips: ["Spread the rope at the bottom", "Keep upper arms still"],
    mistakes: ["Leaning over the weight", "Elbows flaring"],
  },
  {
    slug: "bench-dip",
    name: "Bench Dip",
    primary: "triceps",
    secondary: ["chest", "shoulders"],
    equipment: "bodyweight",
    level: "beginner",
    kind: "compound",
    summary: "Bodyweight triceps exercise you can do anywhere.",
    steps: ["Hands on a bench behind you, legs out in front.", "Bend the elbows to lower your hips.", "Press back up to straight arms."],
    tips: ["Bend knees to make it easier", "Keep your back close to the bench"],
    mistakes: ["Going too deep and straining the shoulders"],
  },
  {
    slug: "skull-crusher",
    name: "EZ-Bar Skull Crusher",
    primary: "triceps",
    secondary: [],
    equipment: "barbell",
    level: "intermediate",
    kind: "isolation",
    summary: "Long-head triceps builder for bigger arms.",
    steps: ["Lie on a bench holding an EZ-bar above your chest.", "Bend the elbows to lower the bar toward your forehead.", "Extend back to straight arms."],
    tips: ["Let the bar travel slightly behind the head for more stretch"],
    mistakes: ["Elbows flaring wide", "Going too heavy"],
  },
  // ---------- legs ----------
  {
    slug: "barbell-back-squat",
    name: "Barbell Back Squat",
    primary: "quads",
    secondary: ["glutes", "hamstrings", "core"],
    equipment: "barbell",
    level: "intermediate",
    kind: "compound",
    summary: "The foundational lower-body strength and muscle builder.",
    steps: [
      "Set the bar on your upper back and step out with feet shoulder-width apart.",
      "Brace your core and sit down between your heels, knees tracking over toes.",
      "Descend until thighs are at least parallel.",
      "Drive up through the whole foot to stand tall.",
    ],
    tips: ["Use safety pins in the rack", "Keep your chest proud"],
    mistakes: ["Knees caving in", "Heels lifting"],
  },
  {
    slug: "goblet-squat",
    name: "Goblet Squat",
    primary: "quads",
    secondary: ["glutes", "core"],
    equipment: "dumbbell",
    level: "beginner",
    kind: "compound",
    summary: "The best way to learn squatting — the weight in front keeps you upright.",
    steps: ["Hold a dumbbell vertically against your chest.", "Squat down between your heels with elbows inside the knees.", "Stand back up by pushing the floor away."],
    tips: ["Pause 1 second at the bottom", "Keep heels planted"],
    mistakes: ["Rounding forward", "Rising onto toes"],
  },
  {
    slug: "leg-press",
    name: "Leg Press",
    primary: "quads",
    secondary: ["glutes"],
    equipment: "machine",
    level: "beginner",
    kind: "compound",
    summary: "Heavy leg training with the back supported.",
    steps: ["Sit with feet shoulder-width on the platform.", "Release the safety and lower until knees reach about 90°.", "Press back up without locking the knees."],
    tips: ["Keep your lower back on the pad"],
    mistakes: ["Lowering so deep the hips curl up", "Locking knees hard"],
  },
  {
    slug: "walking-lunge",
    name: "Walking Lunge",
    primary: "quads",
    secondary: ["glutes", "hamstrings", "core"],
    equipment: "dumbbell",
    level: "beginner",
    kind: "compound",
    summary: "Single-leg strength, balance and a serious glute burn.",
    steps: ["Hold dumbbells at your sides.", "Step forward and lower until both knees are near 90°.", "Push through the front heel and step into the next lunge."],
    tips: ["Take long steps for more glutes"],
    mistakes: ["Front knee caving in", "Short, choppy steps"],
  },
  {
    slug: "leg-extension",
    name: "Leg Extension",
    primary: "quads",
    secondary: [],
    equipment: "machine",
    level: "beginner",
    kind: "isolation",
    summary: "Quad isolation for definition and knee-supporting strength.",
    steps: ["Sit with the pad on your lower shins.", "Extend your legs until straight.", "Lower slowly."],
    tips: ["Squeeze at the top for a second"],
    mistakes: ["Kicking the weight up"],
  },
  {
    slug: "romanian-deadlift",
    name: "Romanian Deadlift",
    primary: "hamstrings",
    secondary: ["glutes", "back"],
    equipment: "barbell",
    level: "intermediate",
    kind: "compound",
    summary: "Builds hamstrings and glutes through a deep hip hinge.",
    steps: ["Stand holding the bar at your hips.", "Push hips back with soft knees, sliding the bar down your thighs.", "Stop when you feel a strong hamstring stretch, then drive hips forward to stand."],
    tips: ["Think 'hips back', not 'bend down'"],
    mistakes: ["Rounding the back", "Squatting it instead of hinging"],
  },
  {
    slug: "dumbbell-romanian-deadlift",
    name: "Dumbbell Romanian Deadlift",
    primary: "hamstrings",
    secondary: ["glutes"],
    equipment: "dumbbell",
    level: "beginner",
    kind: "compound",
    summary: "Beginner-friendly hinge for hamstrings and glutes.",
    steps: ["Hold dumbbells in front of your thighs.", "Hinge at the hips, keeping dumbbells close to your legs.", "Return to standing by squeezing your glutes."],
    tips: ["Keep a flat back throughout"],
    mistakes: ["Letting the dumbbells drift away from the legs"],
  },
  {
    slug: "lying-leg-curl",
    name: "Lying Leg Curl",
    primary: "hamstrings",
    secondary: ["calves"],
    equipment: "machine",
    level: "beginner",
    kind: "isolation",
    summary: "Hamstring isolation that protects knees and improves sprinting.",
    steps: ["Lie face down with the pad above your heels.", "Curl your heels toward your glutes.", "Lower slowly."],
    tips: ["Keep hips pressed into the pad"],
    mistakes: ["Lifting the hips", "Fast, jerky reps"],
  },
  {
    slug: "hip-thrust",
    name: "Barbell Hip Thrust",
    primary: "glutes",
    secondary: ["hamstrings"],
    equipment: "barbell",
    level: "beginner",
    kind: "compound",
    summary: "The top glute builder — great for posture and lower-back health.",
    steps: ["Sit with upper back against a bench and a padded bar over your hips.", "Drive through your heels to lift hips until your body is level.", "Squeeze glutes at the top, then lower."],
    tips: ["Chin tucked, ribs down", "Pause 2 seconds at the top"],
    mistakes: ["Over-arching the lower back"],
  },
  {
    slug: "kettlebell-swing",
    name: "Kettlebell Swing",
    primary: "glutes",
    secondary: ["hamstrings", "core", "cardio"],
    equipment: "kettlebell",
    level: "intermediate",
    kind: "compound",
    summary: "Explosive hip power that doubles as fat-burning conditioning.",
    steps: ["Hike the kettlebell back between your legs.", "Snap your hips forward to float the bell to chest height.", "Let it fall back and hinge again."],
    tips: ["It's a hip hinge, not a squat or an arm raise"],
    mistakes: ["Lifting with the arms", "Rounded back"],
  },
  {
    slug: "standing-calf-raise",
    name: "Standing Calf Raise",
    primary: "calves",
    secondary: [],
    equipment: "machine",
    level: "beginner",
    kind: "isolation",
    summary: "Stronger, bigger calves and more stable ankles.",
    steps: ["Stand with the balls of your feet on the edge of the platform.", "Rise up as high as possible.", "Lower until you feel a deep stretch."],
    tips: ["Pause at the top and bottom"],
    mistakes: ["Bouncing through tiny reps"],
  },
  // ---------- core ----------
  {
    slug: "plank",
    name: "Plank",
    primary: "core",
    secondary: ["shoulders"],
    equipment: "bodyweight",
    level: "beginner",
    kind: "isolation",
    summary: "Builds the bracing strength that protects your back on every lift.",
    steps: ["Forearms under shoulders, body in a straight line.", "Squeeze glutes and brace your abs.", "Hold without letting hips sag."],
    tips: ["Quality over time — 30 strong seconds beats 2 sloppy minutes"],
    mistakes: ["Hips too high or sagging", "Holding your breath"],
  },
  {
    slug: "hanging-knee-raise",
    name: "Hanging Knee Raise",
    primary: "core",
    secondary: [],
    equipment: "bodyweight",
    level: "intermediate",
    kind: "isolation",
    summary: "Lower-abs focus and grip strength in one.",
    steps: ["Hang from a pull-up bar.", "Curl your knees up toward your chest.", "Lower slowly without swinging."],
    tips: ["Tilt the pelvis up at the top"],
    mistakes: ["Swinging for momentum"],
  },
  {
    slug: "dead-bug",
    name: "Dead Bug",
    primary: "core",
    secondary: [],
    equipment: "bodyweight",
    level: "beginner",
    kind: "isolation",
    summary: "Teaches core control — ideal for beginners and back-pain sufferers.",
    steps: ["Lie on your back, arms up, knees at 90°.", "Lower opposite arm and leg while keeping your lower back flat.", "Return and switch sides."],
    tips: ["Exhale fully as you extend"],
    mistakes: ["Lower back lifting off the floor"],
  },
  {
    slug: "cable-crunch",
    name: "Cable Crunch",
    primary: "core",
    secondary: [],
    equipment: "cable",
    level: "beginner",
    kind: "isolation",
    summary: "Loadable ab exercise for visible six-pack muscles.",
    steps: ["Kneel below a high pulley holding a rope by your head.", "Crunch down, bringing elbows toward thighs.", "Return slowly."],
    tips: ["Round the spine — don't just bow at the hips"],
    mistakes: ["Pulling with the arms"],
  },
  // ---------- cardio ----------
  {
    slug: "incline-treadmill-walk",
    name: "Incline Treadmill Walk",
    primary: "cardio",
    secondary: ["glutes", "calves"],
    equipment: "machine",
    level: "beginner",
    kind: "cardio",
    summary: "Low-impact zone-2 cardio that burns fat without hurting recovery.",
    steps: ["Set incline to 8–12% and speed to 4–5.5 km/h.", "Walk without holding the rails.", "Keep it at a pace where you can still talk."],
    tips: ["20–40 minutes after weights works well"],
    mistakes: ["Hanging on the handrails"],
  },
  {
    slug: "stationary-bike-intervals",
    name: "Stationary Bike Intervals",
    primary: "cardio",
    secondary: ["quads"],
    equipment: "machine",
    level: "beginner",
    kind: "cardio",
    summary: "Joint-friendly HIIT for stamina and calorie burn.",
    steps: ["Warm up 5 minutes easy.", "Sprint 30 seconds hard, then 90 seconds easy.", "Repeat 6–8 rounds, then cool down."],
    tips: ["Raise resistance for the sprints"],
    mistakes: ["Going 'medium' on every interval"],
  },
  {
    slug: "burpee",
    name: "Burpee",
    primary: "cardio",
    secondary: ["chest", "quads", "core"],
    equipment: "bodyweight",
    level: "intermediate",
    kind: "cardio",
    summary: "Full-body conditioning with zero equipment.",
    steps: ["Squat and place hands on the floor.", "Jump feet back to a plank and do a push-up.", "Jump feet back in and leap up."],
    tips: ["Step back instead of jumping to make it easier"],
    mistakes: ["Sagging hips in the plank"],
  },
  {
    slug: "skipping-rope",
    name: "Skipping Rope",
    primary: "cardio",
    secondary: ["calves"],
    equipment: "bodyweight",
    level: "beginner",
    kind: "cardio",
    summary: "Cheap, fast, coordination-building cardio.",
    steps: ["Hold handles at hip height.", "Turn the rope from the wrists and hop just high enough to clear it.", "Land softly on the balls of your feet."],
    tips: ["Start with 30 seconds on, 30 off"],
    mistakes: ["Jumping too high", "Using the whole arm"],
  },
];

export const exerciseBySlug = (slug: string) => EXERCISES.find((e) => e.slug === slug);
export const muscleLabel = (m: Muscle) => MUSCLES.find((x) => x.id === m)?.label ?? m;
export const equipmentLabel = (e: Equipment) => EQUIPMENT.find((x) => x.id === e)?.label ?? e;
