import type {
  AffiliateProduct,
  DigitalProduct,
  PaidGuide,
  PaidPlan,
  Advertisement,
  Sponsor,
  LeadFormConfig,
  BusinessListing,
  Coupon,
  PremiumReport,
} from "./types";

const now = new Date().toISOString();
const weekFromNow = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString();
const monthFromNow = new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString();

// Central monetization config — single source of truth, modular, no hardcoded values in components
// IMPORTANT: Never fabricate prices, ratings, reviews, brands. Use placeholders until genuine data supplied.

export const AFFILIATE_PRODUCTS: AffiliateProduct[] = [
  {
    id: "aff-glucometer",
    slug: "digital-glucometer-combo",
    title: "Digital Glucometer + 50 Strips (Demo)",
    description: "Fasting/PP tracking essential for every diabetic home. Demo product — compare accuracy (ISO 15197), strip cost and app sync before buying any brand.",
    category: "Diabetes",
    image: "/og-default.jpg",
    price: 1999,
    originalPrice: 2499,
    currency: "INR",
    affiliateUrl: "#",
    purchaseUrl: "#",
    active: true,
    featured: true,
    priority: 100,
    ctaText: "View Product",
    trackingId: "aff-glucometer-home",
    destination: "merchant",
    createdAt: now,
    updatedAt: now,
    tags: ["diabetes", "monitoring", "glucometer"],
    merchant: "Demo Merchant",
    rating: undefined, // do not fabricate
    discountPercent: 20,
    isAffiliate: true,
    disclosure: "Affiliate link — we may earn a commission at no additional cost to you.",
  },
  {
    id: "aff-bp-monitor",
    slug: "upper-arm-bp-monitor",
    title: "Upper-Arm BP Monitor (Demo)",
    description: "Validated oscillometric monitoring for home averages. Demo product — check ESH/STRIDE validation lists.",
    category: "Blood Pressure",
    image: "/og-default.jpg",
    price: 2999,
    originalPrice: 3999,
    currency: "INR",
    affiliateUrl: "#",
    active: true,
    featured: true,
    priority: 90,
    ctaText: "Check Price",
    trackingId: "aff-bp-home",
    destination: "merchant",
    createdAt: now,
    updatedAt: now,
    tags: ["hypertension", "monitoring"],
    merchant: "Demo Merchant",
    isAffiliate: true,
    disclosure: "Affiliate link — we may earn a commission at no additional cost to you.",
  },
  {
    id: "aff-millet-combo",
    slug: "millet-combo-pack",
    title: "Millet Combo: Foxtail + Barnyard + Ragi (Demo)",
    description: "3-kg starter for rice swaps 4x/week. Unpolished millets with cooking guide.",
    category: "Healthy Foods",
    image: "/og-default.jpg",
    price: 599,
    originalPrice: 799,
    currency: "INR",
    affiliateUrl: "#",
    active: true,
    featured: true,
    priority: 85,
    ctaText: "View Product",
    trackingId: "aff-millet",
    destination: "merchant",
    createdAt: now,
    updatedAt: now,
    tags: ["millets", "diabetes", "nutrition"],
    merchant: "Demo Merchant",
    isAffiliate: true,
    disclosure: "Affiliate link — we may earn a commission at no additional cost to you.",
  },
  {
    id: "aff-yoga-mat",
    slug: "yoga-mat-6mm",
    title: "Anti-Skid Yoga Mat 6mm (Demo)",
    description: "Joint-friendly thickness for beginners and seniors. 6-mm TPE mat with alignment lines.",
    category: "Yoga",
    image: "/og-default.jpg",
    price: 1299,
    originalPrice: 1799,
    currency: "INR",
    affiliateUrl: "#",
    active: true,
    featured: true,
    priority: 80,
    ctaText: "View Product",
    trackingId: "aff-yoga-mat",
    destination: "merchant",
    createdAt: now,
    updatedAt: now,
    tags: ["yoga", "fitness"],
    merchant: "Demo Merchant",
    isAffiliate: true,
    disclosure: "Affiliate link — we may earn a commission at no additional cost to you.",
  },
  {
    id: "aff-whey-protein",
    slug: "whey-protein-1kg",
    title: "Whey Protein 1kg (Demo)",
    description: "25 g protein/scoop for vegetarian muscle and satiety. Demo product — food first; supplements fill gaps only.",
    category: "Supplements",
    image: "/og-default.jpg",
    price: 3499,
    originalPrice: 4499,
    currency: "INR",
    affiliateUrl: "#",
    active: true,
    featured: false,
    priority: 75,
    ctaText: "Check Price",
    trackingId: "aff-whey",
    destination: "merchant",
    createdAt: now,
    updatedAt: now,
    tags: ["protein", "fitness", "nutrition"],
    merchant: "Demo Merchant",
    isAffiliate: true,
    disclosure: "Affiliate link — we may earn a commission at no additional cost to you.",
  },
  {
    id: "aff-mustard-oil",
    slug: "cold-pressed-mustard-oil",
    title: "Cold-Pressed Mustard Oil 5L (Demo)",
    description: "Traditional Indian cooking oil for rotation with groundnut. Demo product — rotate oils and cap visible fat at 3–4 tsp/day.",
    category: "Healthy Foods",
    image: "/og-default.jpg",
    price: 1199,
    originalPrice: 1399,
    currency: "INR",
    affiliateUrl: "#",
    active: true,
    featured: false,
    priority: 60,
    ctaText: "View Product",
    trackingId: "aff-oil",
    destination: "merchant",
    createdAt: now,
    updatedAt: now,
    tags: ["heart", "cooking"],
    merchant: "Demo Merchant",
    isAffiliate: true,
    disclosure: "Affiliate link — we may earn a commission at no additional cost to you.",
  },
];

// Digital Products — PDFs, eBooks, guides, diet plans
export const DIGITAL_PRODUCTS: DigitalProduct[] = [
  {
    id: "dig-diabetes-guide",
    slug: "indian-diabetes-diet-guide",
    title: "Indian Diabetes Diet Guide — 60 Pages (Demo)",
    description: "Educational nutrition resource with thali plates, millet swaps, monitoring checklists. Discuss dietary changes with your qualified healthcare professional.",
    category: "Health Guides",
    image: "/og-default.jpg",
    price: 199,
    originalPrice: 399,
    currency: "INR",
    active: true,
    featured: true,
    priority: 100,
    ctaText: "Download Guide — ₹199",
    trackingId: "dig-diabetes",
    destination: "checkout",
    createdAt: now,
    updatedAt: now,
    tags: ["diabetes", "diet", "thali"],
    format: "PDF",
    pages: 60,
    fileSize: "4.2 MB",
    author: "BHG Editorial Team",
    isDigital: true,
    previewUrl: "/api/monetization/preview/dig-diabetes-guide",
    downloadLimit: 3,
    expiresInHours: 72,
  },
  {
    id: "dig-weight-30d",
    slug: "30-day-indian-weight-management-plan",
    title: "30-Day Indian Weight Management Plan (Demo)",
    description: "Educational 30-day plan with vegetarian thali, protein targets 1.2-1.6g/kg, strength 3x/week. No guaranteed weight loss. Consult professional.",
    category: "Diet Plans",
    image: "/og-default.jpg",
    price: 299,
    originalPrice: 599,
    currency: "INR",
    active: true,
    featured: true,
    priority: 95,
    ctaText: "Get 30-Day Plan — ₹299",
    trackingId: "dig-weight-30d",
    destination: "checkout",
    createdAt: now,
    updatedAt: now,
    tags: ["weight", "diet", "thali"],
    format: "PDF",
    pages: 45,
    fileSize: "3.8 MB",
    author: "BHG Nutrition Team",
    isDigital: true,
    previewUrl: "/api/monetization/preview/dig-weight-30d",
    downloadLimit: 3,
    expiresInHours: 72,
  },
  {
    id: "dig-high-protein-veg",
    slug: "indian-high-protein-vegetarian-diet",
    title: "Indian High-Protein Vegetarian Diet — 40 Pages (Demo)",
    description: "Hit protein 1.2-1.6g/kg vegetarian: dal, soya 52g, paneer 18g, sprouts, curd, whey — thali + tracking.",
    category: "Diet Plans",
    image: "/og-default.jpg",
    price: 149,
    originalPrice: 299,
    currency: "INR",
    active: true,
    featured: true,
    priority: 90,
    ctaText: "Get Guide — ₹149",
    trackingId: "dig-protein-veg",
    destination: "checkout",
    createdAt: now,
    updatedAt: now,
    tags: ["protein", "vegetarian", "diet"],
    format: "PDF",
    pages: 40,
    fileSize: "2.9 MB",
    author: "BHG Nutrition Team",
    isDigital: true,
    previewUrl: "/api/monetization/preview/dig-high-protein-veg",
    downloadLimit: 3,
    expiresInHours: 72,
  },
  {
    id: "dig-ayurveda-herbs",
    slug: "ayurvedic-herbs-reference-guide",
    title: "Ayurvedic Herbs Reference Guide — 50 Herbs (Demo)",
    description: "Evidence-graded herb profiles with safety, interactions, Hindi names. Book ≠ medical advice.",
    category: "Health Guides",
    image: "/og-default.jpg",
    price: 249,
    originalPrice: 499,
    currency: "INR",
    active: true,
    featured: false,
    priority: 80,
    ctaText: "Download Reference — ₹249",
    trackingId: "dig-ayurveda",
    destination: "checkout",
    createdAt: now,
    updatedAt: now,
    tags: ["ayurveda", "herbs", "safety"],
    format: "PDF",
    pages: 80,
    fileSize: "6.1 MB",
    author: "BHG Ayurveda Team",
    isDigital: true,
    previewUrl: "/api/monetization/preview/dig-ayurveda-herbs",
    downloadLimit: 3,
    expiresInHours: 72,
  },
  {
    id: "dig-heart-healthy",
    slug: "indian-heart-healthy-diet-guide",
    title: "Indian Heart-Healthy Diet Guide (Demo)",
    description: "DASH-thali fusion: salt, oil, nuts and fibre tuned for Indian kitchens. Educational resource.",
    category: "Health Guides",
    image: "/og-default.jpg",
    price: 199,
    originalPrice: 349,
    currency: "INR",
    active: true,
    featured: false,
    priority: 75,
    ctaText: "Get Guide — ₹199",
    trackingId: "dig-heart",
    destination: "checkout",
    createdAt: now,
    updatedAt: now,
    tags: ["heart", "DASH", "diet"],
    format: "PDF",
    pages: 50,
    fileSize: "3.5 MB",
    author: "BHG Editorial Team",
    isDigital: true,
    previewUrl: "/api/monetization/preview/dig-heart-healthy",
    downloadLimit: 3,
    expiresInHours: 72,
  },
];

export const PAID_GUIDES: PaidGuide[] = DIGITAL_PRODUCTS.filter((p) => p.category === "Health Guides") as PaidGuide[];
export const PAID_PLANS: PaidPlan[] = DIGITAL_PRODUCTS.filter((p) => p.category === "Diet Plans").map((p) => ({
  ...(p as DigitalProduct),
  guideType: "health-guide",
  planType: p.slug.includes("30-day") ? "30-day" : p.slug.includes("high-protein") ? "high-protein" : "custom",
  durationDays: p.slug.includes("30-day") ? 30 : p.slug.includes("7-day") ? 7 : 14,
})) as unknown as PaidPlan[];

// Advertisements — placeholders, clearly marked
export const ADVERTISEMENTS: Advertisement[] = [
  {
    id: "ad-home-top",
    slug: "ad-home-top",
    title: "Homepage Top Banner — Placeholder",
    description: "Advertisement placeholder — editorial content never influenced by advertisers.",
    category: "General Wellness",
    image: "/og-default.jpg",
    price: 0,
    currency: "INR",
    active: true,
    featured: false,
    priority: 100,
    ctaText: "Advertisement",
    trackingId: "ad-home-top",
    destination: "ad",
    createdAt: now,
    updatedAt: now,
    placement: "homepage_top",
    adType: "banner",
    width: 728,
    height: 90,
  },
  {
    id: "ad-disease-middle",
    slug: "ad-disease-middle",
    title: "Disease Middle In-Article — Placeholder",
    description: "Advertisement placeholder — clearly labeled.",
    category: "General Wellness",
    image: "/og-default.jpg",
    price: 0,
    currency: "INR",
    active: true,
    featured: false,
    priority: 90,
    ctaText: "Advertisement",
    trackingId: "ad-disease-middle",
    destination: "ad",
    createdAt: now,
    updatedAt: now,
    placement: "disease_middle",
    adType: "in-article",
    width: 300,
    height: 250,
  },
  {
    id: "ad-article-bottom",
    slug: "ad-article-bottom",
    title: "Article Bottom Rectangle — Placeholder",
    description: "Advertisement placeholder.",
    category: "General Wellness",
    image: "/og-default.jpg",
    price: 0,
    currency: "INR",
    active: true,
    featured: false,
    priority: 80,
    ctaText: "Advertisement",
    trackingId: "ad-article-bottom",
    destination: "ad",
    createdAt: now,
    updatedAt: now,
    placement: "article_bottom",
    adType: "rectangle",
    width: 300,
    height: 250,
  },
  {
    id: "ad-products-sidebar",
    slug: "ad-products-sidebar",
    title: "Products Sidebar — Placeholder",
    description: "Advertisement placeholder for products sidebar.",
    category: "General Wellness",
    image: "/og-default.jpg",
    price: 0,
    currency: "INR",
    active: true,
    featured: false,
    priority: 70,
    ctaText: "Advertisement",
    trackingId: "ad-products-sidebar",
    destination: "ad",
    createdAt: now,
    updatedAt: now,
    placement: "products_sidebar",
    adType: "sidebar",
    width: 300,
    height: 600,
  },
];

// Sponsors
export const SPONSORS: Sponsor[] = [
  {
    id: "sponsor-demo-1",
    sponsorName: "Demo Health Foods Co.",
    campaign: "Millet Awareness Month",
    description: "Sponsored — promoting millet-based nutrition education. Editorial content remains independent.",
    logo: "/og-default.jpg",
    placement: "homepage_middle",
    ctaText: "Learn More",
    url: "/products/millet-combo-pack",
    startDate: now,
    endDate: monthFromNow,
    active: true,
    priority: 100,
    disclosure: "Sponsored — Paid partnership. Editorial independence maintained.",
    tags: ["millets", "nutrition"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "sponsor-demo-2",
    sponsorName: "Demo Wellness Labs",
    campaign: "Preventive Health Checkup",
    description: "Sponsored — preventive health packages. Does not influence clinical recommendations.",
    logo: "/og-default.jpg",
    placement: "newsletter",
    ctaText: "View Packages",
    url: "/lead",
    startDate: now,
    endDate: monthFromNow,
    active: true,
    priority: 90,
    disclosure: "Sponsored — Paid partnership.",
    tags: ["lab-tests", "preventive"],
    createdAt: now,
    updatedAt: now,
  },
];

// Lead Forms
export const LEAD_FORMS: LeadFormConfig[] = [
  {
    id: "lead-diet",
    title: "Diet Consultation Inquiry",
    description: "Connect with a qualified dietitian/nutritionist for personalized guidance.",
    service: "diet-consultation",
    fields: ["name", "email", "phone", "service", "message", "consent"],
    active: true,
    ctaText: "Request Diet Consultation",
    successMessage: "Thanks! A qualified professional will contact you within 24 hours.",
    createdAt: now,
  },
  {
    id: "lead-fitness",
    title: "Fitness Consultation",
    description: "Fitness coach inquiry — strength, weight management, general wellness.",
    service: "fitness-consultation",
    fields: ["name", "email", "phone", "service", "message", "consent"],
    active: true,
    ctaText: "Request Fitness Consultation",
    successMessage: "Thanks! We'll connect you with a fitness professional.",
    createdAt: now,
  },
  {
    id: "lead-corporate",
    title: "Corporate Wellness Inquiry",
    description: "Corporate wellness programs, health talks, screenings.",
    service: "corporate-wellness",
    fields: ["name", "email", "phone", "service", "message", "consent"],
    active: true,
    ctaText: "Inquire for Corporate Wellness",
    successMessage: "Thanks! Our partnerships team will reach out.",
    createdAt: now,
  },
];

// Business Listings / Providers
export const BUSINESS_LISTINGS: BusinessListing[] = [
  {
    id: "biz-dietitian-delhi-1",
    slug: "dietitian-delhi-demo-1",
    title: "Demo Dietitian — South Delhi (Demo Listing)",
    description: "Demo listing — qualified dietitian for weight management, diabetes education. Credentials not verified in demo. Clearly marked demo.",
    category: "Nutrition",
    image: "/og-default.jpg",
    price: 0,
    currency: "INR",
    active: true,
    featured: true,
    priority: 100,
    ctaText: "View Profile",
    trackingId: "biz-dietitian-1",
    destination: "provider",
    createdAt: now,
    updatedAt: now,
    tags: ["dietitian", "delhi", "demo"],
    providerType: "Dietitian",
    tier: "featured",
    location: "South Delhi, Delhi",
    verified: false,
    credentials: "Demo — M.Sc Nutrition (placeholder, not verified)",
  },
  {
    id: "biz-yoga-pune-1",
    slug: "yoga-instructor-pune-demo-1",
    title: "Demo Yoga Instructor — Pune (Demo)",
    description: "Demo yoga instructor for beginners, seniors. Demo listing — not a medical recommendation.",
    category: "Yoga",
    image: "/og-default.jpg",
    price: 0,
    currency: "INR",
    active: true,
    featured: false,
    priority: 80,
    ctaText: "View Profile",
    trackingId: "biz-yoga-1",
    destination: "provider",
    createdAt: now,
    updatedAt: now,
    tags: ["yoga", "pune", "demo"],
    providerType: "Yoga Instructor",
    tier: "free",
    location: "Pune, Maharashtra",
    verified: false,
  },
  {
    id: "biz-clinic-mumbai-1",
    slug: "clinic-mumbai-demo-1",
    title: "Demo Wellness Clinic — Mumbai (Demo)",
    description: "Demo clinic listing for preventive health. Clearly marked demo, not a medical endorsement.",
    category: "General Wellness",
    image: "/og-default.jpg",
    price: 0,
    currency: "INR",
    active: true,
    featured: true,
    priority: 90,
    ctaText: "View Clinic",
    trackingId: "biz-clinic-1",
    destination: "provider",
    createdAt: now,
    updatedAt: now,
    tags: ["clinic", "mumbai", "demo"],
    providerType: "Clinic",
    tier: "premium",
    location: "Bandra, Mumbai",
    verified: false,
  },
];

// Coupons / Deals
export const COUPONS: Coupon[] = [
  {
    id: "coupon-millet-20",
    slug: "millet-combo-20-off",
    title: "Millet Combo — 20% OFF (Demo Coupon)",
    description: "Demo coupon for millet combo pack. Affiliate link — we may earn commission.",
    category: "Healthy Foods",
    image: "/og-default.jpg",
    price: 479,
    originalPrice: 599,
    currency: "INR",
    active: true,
    featured: true,
    priority: 100,
    ctaText: "Get Coupon",
    trackingId: "coupon-millet-20",
    destination: "merchant",
    createdAt: now,
    updatedAt: now,
    tags: ["millets", "coupon"],
    code: "MILLET20",
    discount: "20% OFF",
    discountPercent: 20,
    merchant: "Demo Merchant",
    affiliateUrl: "#",
    expirationDate: monthFromNow,
    terms: "Demo coupon — expires in 30 days. Terms apply on merchant site.",
  },
  {
    id: "coupon-glucometer-100",
    slug: "glucometer-100-off",
    title: "Glucometer — ₹100 OFF (Demo)",
    description: "Demo coupon for glucometer combo.",
    category: "Medical Devices",
    image: "/og-default.jpg",
    price: 1899,
    originalPrice: 1999,
    currency: "INR",
    active: true,
    featured: false,
    priority: 90,
    ctaText: "Claim Deal",
    trackingId: "coupon-glucometer",
    destination: "merchant",
    createdAt: now,
    updatedAt: now,
    tags: ["glucometer", "diabetes"],
    code: "GLUCO100",
    discount: "₹100 OFF",
    discountAmount: 100,
    merchant: "Demo Merchant",
    affiliateUrl: "#",
    expirationDate: weekFromNow,
    terms: "Demo coupon — limited time.",
  },
  {
    id: "coupon-expired-demo",
    slug: "expired-demo-coupon",
    title: "Expired Demo — Should Be Inactive",
    description: "This coupon is expired and should be auto-marked inactive.",
    category: "General Wellness",
    image: "/og-default.jpg",
    price: 0,
    currency: "INR",
    active: true, // will be auto-marked inactive by logic
    featured: false,
    priority: 10,
    ctaText: "Expired",
    trackingId: "coupon-expired",
    destination: "merchant",
    createdAt: now,
    updatedAt: now,
    tags: ["expired", "demo"],
    code: "EXPIRED",
    discount: "50% OFF",
    discountPercent: 50,
    merchant: "Demo Merchant",
    affiliateUrl: "#",
    expirationDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), // 2 days ago
    terms: "Expired demo.",
  },
];

// Premium Reports — calculator upsell
export const PREMIUM_REPORTS: PremiumReport[] = [
  {
    id: "report-bmi-49",
    slug: "bmi-wellness-report-49",
    title: "Detailed BMI & Wellness Report — ₹49 (Demo)",
    description: "Educational report: BMI interpretation, waist, lifestyle checklist, questions to ask doctor. Not a medical diagnosis.",
    category: "Calculators",
    image: "/og-default.jpg",
    price: 49,
    originalPrice: 99,
    currency: "INR",
    active: true,
    featured: true,
    priority: 100,
    ctaText: "Download Report — ₹49",
    trackingId: "report-bmi",
    destination: "checkout",
    createdAt: now,
    updatedAt: now,
    tags: ["bmi", "report", "wellness"],
    calculatorType: "bmi",
    includes: ["BMI value + category", "Waist guidance", "Lifestyle checklist", "Questions for doctor", "References"],
  },
  {
    id: "report-calorie-99",
    slug: "personalized-nutrition-report-99",
    title: "Personalized Nutrition Report — ₹99 (Demo)",
    description: "Educational report based on calorie calculator: maintenance, deficit, protein 1.2-1.6g/kg, sample thali. Not a prescription.",
    category: "Calculators",
    image: "/og-default.jpg",
    price: 99,
    originalPrice: 199,
    currency: "INR",
    active: true,
    featured: true,
    priority: 95,
    ctaText: "Get Nutrition Report — ₹99",
    trackingId: "report-calorie",
    destination: "checkout",
    createdAt: now,
    updatedAt: now,
    tags: ["calorie", "nutrition", "report"],
    calculatorType: "calorie",
    includes: ["Maintenance calories", "Deficit/surplus guidance", "Protein targets", "Sample thali", "Monitoring checklist"],
  },
  {
    id: "report-bodyfat-99",
    slug: "detailed-wellness-report-99",
    title: "Detailed Wellness Report — ₹99 (Demo)",
    description: "Educational body composition report: body fat %, lean mass, lifestyle recommendations.",
    category: "Calculators",
    image: "/og-default.jpg",
    price: 99,
    originalPrice: 199,
    currency: "INR",
    active: true,
    featured: false,
    priority: 80,
    ctaText: "Download Wellness Report — ₹99",
    trackingId: "report-bodyfat",
    destination: "checkout",
    createdAt: now,
    updatedAt: now,
    tags: ["body-fat", "wellness"],
    calculatorType: "body-fat",
    includes: ["Body fat %", "Lean mass", "Lifestyle recommendations", "Questions for professional"],
  },
];

// Helper: get active sponsors (auto-hide expired)
export function getActiveSponsors(): Sponsor[] {
  const nowTs = Date.now();
  return SPONSORS.filter((s) => {
    if (!s.active) return false;
    const start = new Date(s.startDate).getTime();
    const end = new Date(s.endDate).getTime();
    return nowTs >= start && nowTs <= end;
  }).sort((a, b) => b.priority - a.priority);
}

// Helper: get active coupons (auto-mark expired)
export function getActiveCoupons(): Coupon[] {
  const nowTs = Date.now();
  return COUPONS.filter((c) => {
    if (!c.active) return false;
    const exp = new Date(c.expirationDate).getTime();
    return exp > nowTs;
  }).sort((a, b) => b.priority - a.priority);
}

// Helper: get expired coupons
export function getExpiredCoupons(): Coupon[] {
  const nowTs = Date.now();
  return COUPONS.filter((c) => new Date(c.expirationDate).getTime() <= nowTs);
}

// Helper: affiliate by category
export function getAffiliateByCategory(category: string, limit = 4): AffiliateProduct[] {
  return AFFILIATE_PRODUCTS.filter((p) => p.active && (p.category === category || p.tags?.includes(category.toLowerCase())))
    .sort((a, b) => b.priority - a.priority)
    .slice(0, limit);
}

// Helper: digital products by category
export function getDigitalByCategory(category: string, limit = 4): DigitalProduct[] {
  return DIGITAL_PRODUCTS.filter((p) => p.active && (p.category === category || p.tags?.includes(category.toLowerCase())))
    .sort((a, b) => b.priority - a.priority)
    .slice(0, limit);
}
